### ISSUE TITLE
Support Promises

### ISSUE THREAD

**Issue by zchrykng** [pekim/tedious#139]
It would be really nice if this package supported promises in addition to callbacks.

I will try to come up with a patch, but I have little experience with coffeescript or a code base this large.

**Comment by bretcope** [comment]
Seems like a nice idea, but highly unlikely to be a priority. If the API of Tedious is ever overhauled, it might be something to keep in mind, but for now I'd like to get this out of the open issues list, so I'm closing it.

**Comment by sebastianzebrowski** [comment]
Maybe Blubird's .promisify() could be used?

**Comment by p-rahul** [comment]
Is supporting Promises still being looked into? 

Also, would anyone consider node-mssql a better alt to Tedious? Just curious. TIA.
