### ISSUE TITLE
Use Streams instead of Events

### ISSUE THREAD

**Issue by stephen-bartell** [pekim/tedious#186]
I'm aware that request is no a real stream, just an event emitter.  It would be _very_ advantageous if request streamed.  I've seen it thrown around in a couple threads here that streaming is somewhat planned, like a nice to have just no time to do it.

So, first, is there any solid idea on when that time might come? 
Second, i'm willing to do it, I'm just totally unfamiliar with the codebase. So if you guys are down to have another body in the code, could i get some cheat codes on where to start looking to implement this feature?

please inform either way, a lack of streams is making me throw things at the wall ;) i'd like to help

**Comment by bretcope** [comment]
Some work is being done on this https://github.com/pekim/tedious/pull/225

I'm closing this issue in favor of keeping progress updates on the PR.
