### ISSUE TITLE
DateTime Parameter from string

### ISSUE THREAD

**Issue by ssstuckey** [pekim/tedious#204]
Is there any consideration for allowing DateTime parameters to come in as a string? I am passing dates between systems as a UTC String within JSON and they are not implicitly converted to Date objects.

I resolved this locally by updating lib/data-types.js to check the type and convert to a Date() object before attempting to call getTime().  Here is my updated source for reference:
```javascript
// ...line 175
    writeParameterData: function(buffer, parameter, options) {
      var days, milliseconds, seconds, threeHundredthsOfSecond;
      if (parameter.value != null) {
        //** Update start
         if (typeof parameter.value === "string") { //if its a string, try to parse it for convenience
          parameter.value = new Date(parameter.value); 
        }
        //** update end
        if (options.useUTC) {
// ...
```

While that works fine for my personal scenario, as a better long term solution, maybe detect if the param value is of the correct type and if not add the overhead of deciding what type to make it and how to get it there in another method.

I considered just forking and making the update, but before I go stir your coffee script I wanted to find out if this is a no-no for you from a semantics perspective. Also, I haven't had a chance to play with any coffee script, so I have no business poking around in your source code yet.

**Comment by patriksimek** [comment]
String to date type coercion was added in #245.
