### ISSUE TITLE
NTLM Login problem

### ISSUE THREAD

**Issue by lloydcotten** [pekim/tedious#207]
Hi,

Are there any tricks to getting the NTLM authentication to work (such as FQDN, formats, TDS versions, etc)?  No matter what I try I get:

    Login failed. The login is from an untrusted domain and cannot be used with Windows authentication.

My config looks like this:

    {
      userName: 'my_domain_user'",
      password: 'my_domain_password",
      domain: 'my.fq.dn',
      server: '192.168.xx.xx',
      options: { database: 'my_db' }
    }

I've also tried using non-FQDN for the domain.  No difference.  It works if I remove `domain` and changed to SQL Server user.

Any ideas?  Thanks!

**Comment by bretcope** [comment]
Note that there is a potential fix which may be merged in soon. See PR #228
