### ISSUE TITLE
Logon failed for login 'username' due to trigger execution.

### ISSUE THREAD

**Issue by tuananh** [pekim/tedious#221]
I don't know what trigger this error though. I have no problem connecting to a dev server with `tedious` but when connect to one of my production server, i got this.

Not sure if this is a bug though.

**Comment by bretcope** [comment]
Closing as no-repro.

**Comment by hirvindev** [comment]
+1

**Comment by hynese** [comment]
+1

When trying to access a MSSQL where I don't have SELECT permission but I do have access to a number of stored procedures.

**Comment by Prashu33** [comment]
+1

**Comment by danforejtek** [comment]
I am having same problem. I have test and prod DB servers on test everything works fine but on prod I get this error `Logon failed for login 'awRepossessedCars' due to trigger execution.` while trying to connect to DB.
Database properties are exactly the same.

**Comment by Areli16** [comment]
I am tring to add a new project to my visual studio 2022's project,wo selected the serverbased database,but it gave me error,
Logon failed for login 'GANYU\Areli' due to trigger execution.
Changed database context to 'master'.
Changed language setting to us_english.

**Comment by MichaelSun90** [comment]
Hi @Areli16  found this page, not sure if it will help you. https://dba.stackexchange.com/questions/218811/logon-failed-for-login-due-to-trigger-execution
