### ISSUE TITLE
TLS Negotiation bug causes redirected connections to fail on redirect

### ISSUE THREAD

**Issue by christopheranderson** [pekim/tedious#222]
When you are redirected on your initial connection, if you've already negotiated SSL once, it won't wait for SSL negotiation to complete before trying to process (in my case) the Login7 message, where it will crash. I fixed this on my local driver by resetting the tlsNegotiationComplete state - see below:
```coffee
message: ->
          if  @tlsNegotiationComplete
            @tlsNegotiationComplete = false
            @transitionTo(@STATE.SENT_LOGIN7_WITH_STANDARD_LOGIN)
          else
```

This may not be the best way for this to work. You may want to reset this when starting the TLS Negotiation, for instance:

```coffee
enter: ->
          @tlsNegotiationComplete = false
```

FYI - There is another issue #223 related to redirect failing when there is a different server url you're redirected to.

**Comment by sandorfr** [comment]
I believe I'm facing the same issue as you do with the latest sql azure version. After the redirection occurs it tries to login again and fails with message "Unrecognized token 20 at offset 1".

**Comment by sandorfr** [comment]
I tried your second fix and it appears to fix this issue. I am now struggling with a server name issue...

**Comment by christopheranderson** [comment]
Confirmed, "Unrecognized token 20 at offset 1" is the error I saw being created for this bug. Should have included that in my original message. :) #223 addresses the server name issue (with a suggested, tentatively working on SQL Azure v12 fix).

**Comment by bretcope** [comment]
Can someone make a pull request to address these issues?

**Comment by christopheranderson** [comment]
Roger. I'll give it a shot tonight/tomorrow.

**Comment by bretcope** [comment]
Fixed via https://github.com/pekim/tedious/pull/224
