### ISSUE TITLE
Cannot easily parse error number from error object on sql request

### ISSUE THREAD

**Issue by ashelley** [pekim/tedious#226]
Hello,

I'm looking for a way to programatically deal with database errors.  For instance I would like to easily detect when a unique key violation occurs.  

Currently on this line:

https://github.com/pekim/tedious/blob/master/src/connection.coffee#L312

```
@request.error = RequestError token.message, 'EREQUEST'
```

we seem to lose token.number (in this case it would be 2627);

if the code was like this:

```
@request.error = RequestError token.message, 'EREQUEST'
@request.error.number = token.number;
```

it would offer the ability to detect this error more easily in code instead of having to regex the error message.

It could be that there is already a good way to deal with this by adding the event listener to to errorMessage on the connection and doing this:

```
connection.on('errorMessage', function(token) {
	connection.request.error.token = token;
});
```

however because the errorMessage event is emitted before setting the error here:

https://github.com/pekim/tedious/blob/master/src/connection.coffee#L309

```
    @tokenStreamParser.on('errorMessage', (token) =>
      @emit('errorMessage', token)
      if @loggedIn
        if @request
          @request.error = RequestError token.message, 'EREQUEST'
      else
        @loginError = ConnectionError token.message, 'ELOGIN'
    )
```

The above strategy of using the eventListenner on the connection to preserve the actual error code can't work.

Is there a good way for me to implement using the actual token.number for error handling in this driver?

Thanks,

-Adam

**Comment by bretcope** [comment]
I think you're right. Why don't you put together a pull request and re-submit.

**Comment by ashelley** [comment]
Sounds good.  I will look at this closer and see if I can create a comprehensive patch to look at for discussion.  Thank you for the feedback.
