### ISSUE TITLE
Add Arthur Schreiber as Collaborator

### ISSUE THREAD

**Issue by bretcope** [pekim/tedious#229]
@pekim we've been [discussing](https://github.com/pekim/tedious/pull/225#issuecomment-69480565) adding @arthurschreiber as a collaborator. Would you mind adding him on github and npm? Or at least on github; I think I can add him on npm.

Aurther, as far as becoming a maintainer is concerned, there are a few things I would say:

1. Make sure you read #177 which describes how we version releases.
2. Obviously you should git-tag any npm release (`npm version`), and always update the [changelog.html](https://github.com/pekim/tedious/blob/gh-pages/changelog.html) on the `gh-pages` branch.
3. Always present breaking changes for discussion before moving forward with them (just like you did today).

If you have any questions, ideas, or are looking for ideas, let us know. Thanks for helping advance the project. It is greatly appreciated by everyone.

**Comment by pekim** [comment]
No problem. Added as a colaborator on this project, and to npm as an additional package owner.

**Comment by bretcope** [comment]
Great. Thank you.

**Comment by arthurschreiber** [comment]
Sweet, thanks! :smile:
