### ISSUE TITLE
"useUTC: false" needs to apply to date, time, datetime2 data types

### ISSUE THREAD

**Issue by fmich** [pekim/tedious#237]
The "useUTC" parameter only applies to fields with a data type of datetime or smalldatetime.  It does not seem to apply for the data types of date, time, or datetime2.  (It also doesn't apply to datetimeoffset, but this particular data type is supposed to supply the timezone anyway.)

My workaround is to use a SQL query to convert my date and my time fields to datetime fields, but I have several of those across my customers' tables.  Can we make the configuration setting "useUTC: false" apply to date, time, and datetime2 data types to return local dates and times instead of UTC dates and times?

**Comment by patriksimek** [comment]
Fixed in upcoming release.
