### ISSUE TITLE
Segmentation fault (core dumped) - Node 0.12.0 / iojs 1.2

### ISSUE THREAD

**Issue by ManRueda** [pekim/tedious#247]
Hi, with the las release of Node (v0.12.0), node crashes when i want to make a request. Debugging i found the line that throws the error, is the 243 of writable-tracking-buffer.js

```javascript
this.buffer.write(value, this.position, encoding);
```

But, there are something odd with the error, not always crash...

With this query, 'SELECT name FROM sys.databases', crash.
But with this one, 'select 1 as number', works fine.

I think, maybe, it a encoding problem... crashes when try to encode the query into the buffer with the 'ucs2' encode.

Thank!!

**Comment by ManRueda** [comment]
The problem only appear with a x64 local compilation. With the binary of the site work "fine" (i have some no related issues).

Thanks!

**Comment by shernshiou** [comment]
Hi do you still encounter segmentation fault?

```javascript
var Connection = require('tedious').Connection;

var config = {
  userName: 'mssql',
  password: 'mssql',
  server: '192.168.88.8'
};

var connection = new Connection(config);

connection.on('connect', function (err) {
  console.log(err);
});
```

[1]    8104 segmentation fault (core dumped)

I get core dump when executing it from linux to windows machine. It is fine at local windows machine. However, it was fine 2 months ago.

**Comment by arthurschreiber** [comment]
This might be related to https://github.com/nodejs/node/issues/2457.

Where is your node version from?

**Comment by shernshiou** [comment]
@arthurschreiber v0.12.7

**Comment by arthurschreiber** [comment]
I'm closing this now, as I believe this was related to nodejs/node#2457 and is not something `tedious` specific.

Feel free to re-open if you still see this issue on recent Node.js versions.
