### ISSUE TITLE
DART pub required

### ISSUE THREAD

**Issue by hasan3ysf** [pekim/tedious#255]
Hi..
Can you make same thing for Dartlang.

I tried to make this as "pull request" but could not.

thanks

**Comment by arthurschreiber** [comment]
I'm not even sure what to do here. `tedious` is written in CoffeeScript, although we're currently in the process of moving it to next-gen JavaScript.

I'm not familiar with Dart, and unless some Dart-Expert wants to tackle this, there's other topics that need to be attended to before we can spend any time working on Dart support.
