### ISSUE TITLE
implicit transactions

### ISSUE THREAD

**Issue by bradenpowers** [pekim/tedious#256]
I looked through the documentation and I didn't see anywhere where I could turn off implicit transactions.  Is this on the roadmap?

**Comment by bretcope** [comment]
Are you sure they're on? We explicitly set them to off in the initial sql calls (see [src/connection.coffee](https://github.com/pekim/tedious/blob/71f2be71a5bc146131905f29ef4aa4fbac46bdcf/src/connection.coffee#L692)) The only thing I know of which implicitly turns them on is `SET ANSI_DEFAULTS ON`, which we're not doing. Ideally, we should give you a way to set it to on, but we don't have that feature yet.
