### ISSUE TITLE
Note about Azure SQL DB v12 Support in 1.8.1 or higher

### ISSUE THREAD

**Issue by christopheranderson** [pekim/tedious#258]
A couple of people in Azure have included me on incidents where folks were trying to use old tedious drivers with their v12 platform and it gets escalated to their engineering team. Is it a good idea to put a note under ["SQL Server Support"](http://pekim.github.io/tedious/index.html) to alert people to this?

**Comment by bretcope** [comment]
If you'd care to make a pull request, I'd be happy to merge it. Documentation is on the `gh-pages` branch.

**Comment by bretcope** [comment]
Also, if you, or someone from Microsoft is interested in becoming a maintainer, please let us know.

**Comment by christopheranderson** [comment]
Created the minor edit. I'm happy to be a maintainer to help with the Azure compat stuff. We're working to improve our OSS support a bit more, so I expect a few more changes.

**Comment by arthurschreiber** [comment]
Hey @christopheranderson,

I've already mentioned this in another issue, but could you see if Microsoft could spare a few Azure SQL database for us to use during our CI builds?

I don't personally use Azure SQL, but having access to an instance for our CI builds would already go a long way to help us improve and fix tedious to support Azure SQL.

**Comment by arthurschreiber** [comment]
I think this is also referencing #262 and will be fixed once #309 gets merged.

**Comment by christopheranderson** [comment]
Yeah, I think I can get that going for you. Email me at chrande *at* Microsoft.com and I'll get the right person involved with this. There is a now a dedicated PM for these drivers, and I'm sure he'd love to help.

**Comment by arthurschreiber** [comment]
Fixed by #309 and #310. Will be released in `1.11.5` and `1.12.3`.
