### ISSUE TITLE
Is it possible to use trigger using Tedious?

### ISSUE THREAD

**Issue by zevsuld** [pekim/tedious#263]
I want to use mssql trigger on my project, is there any way to use trigger in Tedious

**Comment by christopheranderson** [comment]
Are you talking about database side triggers? (like: https://msdn.microsoft.com/en-us/library/ms189799.aspx) You use those today via tedious or any other means of executing SQL on your database.

**Comment by zevsuld** [comment]
@christopheranderson yes I am talking about side triggers, I want to get only updated data from a table using DML trigger(INSERT event) via tedious. Is it possible? 
I am not very data base person , I just wondering it is possible or not.

**Comment by christopheranderson** [comment]
The trigger is on the database, not the driver.  You use the create trigger statement and it will execute SQL for every insert statement. This works with tedious, but tedious doesn't have any special mechanics to implement it.
________________________________

**Comment by zevsuld** [comment]
@christopheranderson thank you for the explanation. I will try what I can do with trigger and tedious.
So closing this issue now. 
Thanks again!!!
