### ISSUE TITLE
Method getTime() does not exist issue with TYPES.DateTime

### ISSUE THREAD

**Issue by rbreaves** [pekim/tedious#265]
I believe it is around line 261 of file data-types.js or 182 in the source. 

The parameter.value.getTime() has no method, because parameter.value is just a literal number value. Parameter.value needs to be inserted into a new object in the same manner as what is done in DateTime2 aka "time = new Date(+parameter.value)".

Once I made that change to DateTime in data-types.js everything worked properly.

**Comment by bretcope** [comment]
You're trying to pass a number as a date value? If so, that's not supported by tedious, nor do I expect we would accept such a merge request. Tedious should support either `Date` objects or date-string literals as date parameters. If you've found a bug in that, then please post code.

**Comment by rbreaves** [comment]
Ah, ok I see what you are saying. I was passing a literal number that was properly formatted just as a test. Didn't think about creating a date object before passing it directly.
