### ISSUE TITLE
ConnectionTimeout

### ISSUE THREAD

**Issue by furyscript** [pekim/tedious#266]
Hi all,

I recently have this error when i try to start nodejs backend:

```
events.js:72
        throw er; // Unhandled 'error' event
              ^
ConnectionError: Failed to connect to xxx.xxx.xxx.xxx:undefined in 15000ms
    at Connection.connectTimeout (/opt/node/app04/node_modules/tedious/lib/connection.js:709:26)
    at null._onTimeout (/opt/node/app04/node_modules/tedious/lib/connection.js:3:59)
    at Timer.listOnTimeout [as ontimeout] (timers.js:112:15)

```

Anyone have a solution??

It's seems to be solved by this:
```
sqlConnectionPool.on("error", function(err) { console.error(err.stack); });
```
So I catch the error event...
Is it possible???

#EDIT 
Now the event.js exception not appears, but it still to show ConnectionError
so issue not resolved...

**Comment by furyscript** [comment]
It's seems to be solved by this:
```
//app.use(express.static('public'));
app.use(express.static(__dirname + '/public'));
```
Is it possible???

**Comment by furyscript** [comment]
up

**Comment by Nick-Riggs** [comment]
Had the same issue today, dug through the code and it seems to query the SQL Server Browser service for the instance. In my case, I didn't have that service running so that was the connection issue - it wasn't an issue connecting to the actual database. So ensure that your SQL Server Browser service is running.

**Comment by arthurschreiber** [comment]
That can't be quite right. The Server Browser is only queried if a certain config setting is set or not set (as I'm on my phone, I can't check right now).

**Comment by Nick-Riggs** [comment]
Here is my config.

var config = {
        server: "localhost",
        database: "database",
        user: "xxx",
        password: "xxx",
        options: {
            instanceName: "sqlexpress",
        }
    };

I tracked it to this line of code to figure out I needed to start the SQL Server Browser service:

https://github.com/pekim/tedious/blob/master/src/instance-lookup.coffee#L56

**Comment by bretcope** [comment]
@furyscript can you confirm whether you ever worked out your problem? There was very little information in your post to understand what might be the issue. I'm going to close this, but it can be reopened if necessary.

**Comment by arthurschreiber** [comment]
@Nick-Riggs If you don't specify a port manually, it'll try to get the port based on the instancename from the Server Browser.

**Comment by furyscript** [comment]
I will probably resolve with options `connectionTimeout: 0` @bretcope
