### ISSUE TITLE
Tedious on Red Hat Enterprise Linux

### ISSUE THREAD

**Issue by meet-bhagdev** [pekim/tedious#270]
Does Tedious need any special configurations for Red Hat Enterprise Linux? I could not find any documentation on the repository regarding this, thus filing an issue.
Thanks for your help!

**Comment by lloydcotten** [comment]
Tedious will run pretty much anywhere node.js will run.  You can find information about node.js on RHEL here: https://github.com/joyent/node/wiki/Installing-Node.js-via-package-manager#enterprise-linux-and-fedora

There's nothing special for Tedious, except using it within your node.js application.

**Comment by meet-bhagdev** [comment]
Thanks for the prompt response :) Appreciate it!
