### ISSUE TITLE
Multiple stored procedures using tedious

### ISSUE THREAD

**Issue by ptarpan** [pekim/tedious#280]
How can I call multiple stored procedures within a single "file"? I am using the tedious driver and the tedious docs I looked at only show a sinlge stored proc per "call/file".

**Comment by ptarpan** [comment]
here's what my req looks like: 
var TYPES = require('tedious').TYPES;

  var request = new Request('get_addresses', function(err) {
    ....
  });

  request.addParameter('name', TYPES.VarChar, 'Fred');
  request.addParameter('age', TYPES.Int, 42);

  connection.callProcedure(request);

**Comment by bretcope** [comment]
To my knowledge, you simply need to make two requests.

**Comment by ptarpan** [comment]
Makes sense. I am in the process of testing this but can let you know what happens once I have something that "works".
