### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by juanmiguelRuaDev** [pekim/tedious#284]
When I try to execute any statement against a SQLServer since a Debian (wheesy), the following message is thrown and the statement is not executed:

```
Segmentation fault
```

Probably is caused by the driver but I'm not sure.

**Comment by arthurschreiber** [comment]
That would be... very weird. I can't imagine how the `tedious` library could cause the node.js binary to segfault, as we don't provide any binary component.

Can you provide us with more information (which node.js version, tedious version, any stack trace?). Did you try any other Node.JS or iojs versions? Do you have a reproducible test case?

**Comment by juanmiguelRuaDev** [comment]
Ohh , It only occurs from a virtual-machine (virtual box) with NAT connection... Possibly my VM have error or misconfigurations; In any case, you may close this issue.

Thank you for you early answer.

Best Regards,

**Comment by bretcope** [comment]
@juanmiguelRuaDev for future reference, you can always close your own issues.
