### ISSUE TITLE
Cannot connect to SQL Azure database

### ISSUE THREAD

**Issue by TyrionLanister** [pekim/tedious#294]
Hej  @rossipedia @arthurschreiber  @vvo
 I am connecting to an Azure database. But I  am receiving connnection error with code: Elogin
>name: 'ConnectionError',
  message: 'Login failed for user \'d*******\'.',
  code: 'ELOGIN' 

```
var config = {
    userName: '****@*****.com',
    password: '****',
    server: '******.database.windows.net',
    options: { encrypt: 'true', database: 'sensorData'}};
```
Detailed log is here=>
>
connected to abcd.database.windows.net:1433
Connected to Database sensorData
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x002F, spid:0x0000, packetId:0x01, window:0x00
  0000  00001A00 06010020 00010200 21000103 00220004 04002600 01FF0000 00010001  ....... ....!... ."....&. ........
  0020  01000000 000000  .......
  PreLogin - version:0.0.0.1 1, encryption:0x01(ON), instopt:0x00, threadId:0x00000000, mars:0x00(OFF)
State change: Connecting -> SentPrelogin
Connected to Database sensorData
Received
  type:0x04(TABULAR_RESULT), status:0x01(EOM), length:0x002B, spid:0x0000, packetId:0x01, window:0x00
  0000  00001A00 06010020 00010200 21000103 00220000 04002200 01FF0B00 04DF0002  ....... ....!... ."....". ........
  0020  010000  ...
  PreLogin - version:11.0.4.223 2, encryption:0x01(ON), instopt:0x00, threadId:0x00000000, mars:0x00(OFF)
Connected to Database sensorData 
Login7 - TDS:0x74000004, PacketSize:0x00001000, ClientProgVer:0x00000000, ClientPID:0x0000340C, ConnectionID:0x00000000
           Flags1:0xE0, Flags2:0x00, TypeFlags:0x00, Flags3:0x08, ClientTimezone:-120, ClientLCID:0x00000409
           Hostname:' ', Username:' ', Password:' ', AppName:'Tedious', ServerName:'abc.database.windows.net', LibraryName:'Tedious'
           Language:'undefined', Database:'sensorData', SSPI:'', AttachDbFile:'', ChangePassword:''
State change: SentPrelogin -> SentTLSSSLNegotiation
Connected to Database sensorData
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0145, spid:0x0000, packetId:0x01, window:0x00
 Connected to Database sensorData
Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0DED, spid:0x0000, packetId:0x01, window:0x00
 Connected to Database sensorData
Sent
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x00AE, spid:0x0000, packetId:0x01, window:0x00
  0000  16030100 66100000 62610404 89529B89 5A209E37 B1443BD0 BF9FDA0B 5B6BED84  ....f... ba...R.. Z .7.D;. ....[k..
  0020  85D42CD3 05686E90 8FC18968 C3DCB1E4 39ECB53F 118F49CE C652876B 2B99DC35  ..,..hn. ...h.... 9..?..I. .R.k+..5
  0040  A547C90F 9201D64C 4EADD5A8 3ABB1377 FC87F4CE 062DA2B9 DC9BA02D C926B803  .G.....LN...:..w.....-.. ...-.&..
  0060  27CBC849 82831957 5CAACF14 03010001 01160301 00306417 065D1796 B0DDDF77  '..I...W\....... .....0d. .].....w
  0080  CA62DEDF AF8AFE52 547172C0 51BB58E9 BD252B64 753D415D FDEB513D DA848499  .b.....RTqr.Q.X. .%+du=A]..Q=....
  00A0  29925000 6787  ).P.g.
Connected to Database sensorData
Received
  type:0x12(PRELOGIN), status:0x01(EOM), length:0x0043, spid:0x0000, packetId:0x01, window:0x00
  0000  14030100 01011603 010030F9 2601E838 5261DD93 4A950896 B55E959F BA78B84F  ........ ..0.&..8Ra..J... .^...x.O
  0020  4FEA6B22 92265B0C A01687B1 F6154ECB 42438F60 C01D0022 B33334  O.k".&[. ......N. BC.`...".34
TLS negotiated (ECDHE-RSA-AES256-SHA, TLSv1/SSLv3)
State change: SentTLSSSLNegotiation -> SentLogin7WithStandardLogin
Connected to Database sensorData
Received
{ number: 18456,
  state: 1,
  class: 14,
  message: 'Login failed for user \'*****\'.',
  serverName: ' ',
  procName: '',
  lineNumber: 1,
  name: 'ERROR',
  event: 'errorMessage' }
{ number: 40608,
  state: 1,
  class: 10,
  message: 'This session has been assigned a tracing ID of \'89796195-3696-42c1-a1ae-2bec2f258328\'.  Provide this tracing ID to customer support when you need assistance.',
  serverName: ' ',
  procName: '',
  lineNumber: 1,
  name: 'INFO',
  event: 'infoMessage' }
{ name: 'DONE',
  event: 'done',
  more: false,
  sqlError: true,
  attention: false,
  serverError: false,
  rowCount: undefined,
  curCmd: 0 }
State change: SentLogin7WithStandardLogin -> Final
connection to abc.database.windows.net:1433 closed
State is already Final "

I am new to tedious. Any help will be greatly appreciated.
@bretcope  Is there any  updates on documentation for connecting to azure.

**Comment by christopheranderson** [comment]
Can you login with that username and password via Visual Studio or some other SQL client? It doesn't look, initially, like a driver issue.

**Comment by arthurschreiber** [comment]
I don't use Azure, unfortunately. @christopheranderson I know Microsoft is really generous towards Open Source projects, I'm involved in a different project and Microsoft is paying for AppVeyor and some other stuff. I know we're not the "offical" Microsoft TDS Driver, but would it be possible to get funding for some Azure cloud databases that we could use to perform our builds against?

**Comment by TyrionLanister** [comment]
Thanks. Connection is working fine. 
Azure server gives  "show connection setting" in right hand side of dashboard for database.
