### ISSUE TITLE
Windows Domain Authentication appears to have stopped working

### ISSUE THREAD

**Issue by kiwans** [pekim/tedious#295]
I was trying to use this library to connect to a MSSQL Server 2014 instance using a Domain login from a unix system. I kept getting a Cannot Login error when using version 1.12.1 which was the latest to install from NPM. I decided to downgrade to 1.10.0 as someone said they used that version for their project to see if I had any success logging in, which I did. From there I upgraded to each version listed in the changelog until I got the error again which was version 1.12.0 where a bunch of dependencies were updated to the latest version. 

To elaborate on my findings, I inspected my network traffic to see the authentication requests between my client and server and found that the SQL server was sending a challenge response back, but the client just seems to stop and not send back the NTLMSSP_AUTH that the server is looking for.

**Comment by arthurschreiber** [comment]
This might be another problem stemming from the refactoring I made in #285 together with missing test code. I'll take a look and see what I can find. Really sorry about that. :disappointed:

**Comment by kiwans** [comment]
No worries :) This is a small project I'm working on so using a slightly older version for now is just fine. Thank you!

**Comment by arobson** [comment]
@arthurshrieber - I can verify that 0.12.0 is when the break was introduced. Our code that worked in prod stopped as soon as we tried rolling from 0.11.4. I haven't had time to try tracking it down yet but looks to be something with the handshake.

**Comment by arthurschreiber** [comment]
@arobson @kiwans Thanks for the reports. I'm looking into the issue right now. If I find what I've broken, I'll publish a fixed version asap. :smile:

**Comment by arthurschreiber** [comment]
Can one of you guys do me a favor and try the following patch?

In `lib/token/sspi-token-parser.js`, can you change line `13` from `return parser.readBuffer(3);` to `return parser.readBuffer(2);` and let me know whether that works for you?

**Comment by kiwans** [comment]
Yeah that seems to have fixed it :) Upgraded back to 1.12.1, made that modification and was able to login successfully.

**Comment by arthurschreiber** [comment]
Thanks for verifying. I'll prepare a PR with the fix and updated test cases in the next hour or so, and release `1.12.2` shortly afterwards.

Thanks for the bug report!

**Comment by kiwans** [comment]
Thanks for the prompt response and fix!

**Comment by arthurschreiber** [comment]
@kiwans I probably won't get to it today anymore. I'm off for the next few days, so it'll take me until early next week to get this pushed out. I'm really sorry about that. :disappointed:

**Comment by kiwans** [comment]
I'm not in a rush haha. I'll keep your fix in place until it's official. Enjoy your time off! :smile:

**Comment by arthurschreiber** [comment]
Thanks! :smile:

**Comment by clshortfuse** [comment]
+1 was going crazy since I just had finished installation connect-mssql and relealized all my sql connections stopped working.

**Comment by arthurschreiber** [comment]
Hey all. I'm working on getting this fixed right now, I think I'll be able to publish a new release today.

**Comment by arthurschreiber** [comment]
I just release 1.12.2, which includes a fix for this issue. Thanks for the report and your patience!

**Comment by arobson** [comment]
@arthurschreiber - looks like there is still an issue with the latest version. I'm getting the following stack trace:

```
TypeError: must start with number, buffer, array or string
    at new Buffer (buffer.js:67:11)
    at NTLMResponsePayload.ntHash (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/ntlm-payload.js:152:21)
    at NTLMResponsePayload.ntv2Hash (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/ntlm-payload.js:143:17)
    at NTLMResponsePayload.lmv2Response (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/ntlm-payload.js:130:17)
    at NTLMResponsePayload.createResponse (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/ntlm-payload.js:65:21)
    at new NTLMResponsePayload (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/ntlm-payload.js:14:22)
    at Connection.sendNTLMResponsePacket (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/connection.js:861:15)
    at Connection.STATE.SENT_LOGIN7_WITH_NTLM.events.receivedChallenge (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/connection.js:205:16)
    at Connection.dispatchEvent (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/connection.js:752:59)
    at Connection.processLogin7NTLMResponse (/git/labs/seriate/node_modules/mssql/node_modules/tedious/lib/connection.js:927:19)
```

Going to take a look myself but wanted to get you feedback ASAP.

**Comment by arthurschreiber** [comment]
@arobson Thanks! This is weird. I even added an integration test that successfully passes on my machine. I'm taking a look now.

**Comment by arobson** [comment]
@arthurschreiber line 152 of the NTLM payload module is getting an `undefined` in place of the password hash it expects. Still digging...

**Comment by arthurschreiber** [comment]
That is called when a new `NTLMResponsePayload` is created in `connection.coffee` on line 642. The `password` value is taken from your config. Are you sure you have a password configured?

**Comment by arobson** [comment]
@arthurschreiber - ugh, yeah, I had a messed up configuration. Sorry for the false alarm :finnadie:

**Comment by arthurschreiber** [comment]
No worries. The failure message could be a lot clearer than the error you got.

**Comment by kiwans** [comment]
Upgraded to 1.12.2 today and have experienced no issues. Thank you for the quick turn around on this issue! :smile:
