### ISSUE TITLE
bulkLoad doesnt work with datetime2 variable

### ISSUE THREAD

**Issue by TyrionLanister** [pekim/tedious#299]
I am using bulkload instance to perform bulk insert. My primary key is datetime2 which is in the format
YYYY-MM-DD Hour:Min:Sec:Milisec  for e.g (2015-08-14 6:33:13.613)
```
    bulkLoad.addColumn('TimeStamp', TYPES.DateTime2, { nullable: false })
```
SQl server/Tedious understands them as  (0001-01-01 00:00:00.0000000).

So I get this error
  >
{ [RequestError: Violation of PRIMARY KEY constraint 'PK__c4be8470__B76142634D4D8C7E'. Cannot insert duplicate key in object 'dbo.c4be84706006'. The duplicate key value is (0001-01-01 00:00:00.0000000).]
  name: 'RequestError',
  message: 'Violation of PRIMARY KEY constraint \'PK__c4be8470__B76142634D4D8C7E\'. Cannot insert duplicate key in object \'dbo.c4be84706006\'. The duplicate key value is (0001-01-01 00:00:00.0000000).',
  code: 'EREQUEST',
  number: 2627,
  state: 1,
  class: 14,
  serverName: 'rcxpnnk',
  procName: '',
  lineNumber: 1 }
 bulkLoad inserted 0 rows
fillTable Finished

I can insert these tuples one by one with insert command.

**Comment by bretcope** [comment]
I'm guessing there's a problem in how you're creating Date objects to feed to the bulk load, because I've just tested on Tedious 1.12.2 and Node 0.12.7 and had no problems bulk-loading into a DateTime2 column.

I created a database called "Scratch" and added this table:

```sql
create table DateTest
(
	Date datetime2(7) not null,
	CONSTRAINT PK_DateTest PRIMARY KEY CLUSTERED (Date Asc)
)
```

And ran this code:

```js
var Connection = require('tedious').Connection;
var Request = require('tedious').Request;
var TYPES = require('tedious').TYPES;

var config = {
	userName: 'user',
	password: 'pass',
	server: 'localhost',
	options: {
		database: 'Scratch'
	}
};

var conn = new Connection(config);

conn.on('connect', function (err)
{
	if (err)
		throw err;

	var bulkLoad = conn.newBulkLoad('DateTest', function (error, rowCount)
	{
		if (error)
			throw error;
		
		console.log('inserted %d rows', rowCount);
	});

	bulkLoad.addColumn('date', TYPES.DateTime2, {nullable: false});

	bulkLoad.addRow({date: new Date('2015-01-01')});
	bulkLoad.addRow({date: new Date('2015-01-02')});

	conn.execBulkLoad(bulkLoad);
});
```

Afterwards, `select * from DateTest` returns:

```
2015-01-01 00:00:00.0000000
2015-01-02 00:00:00.0000000
```

**Comment by TyrionLanister** [comment]
Thanks. It works as you described.
