### ISSUE TITLE
request.on('done') not firing in 1.12 versions

### ISSUE THREAD

**Issue by jeremydiviney** [pekim/tedious#304]
This event doesn't seem to fire any longer in the latest 1.12 versions

**Comment by arthurschreiber** [comment]
A quick check over the test suite tells me that there is not a single test case for this functionality. :disappointed: There's test cases for `doneInProc` though, and these two share the same implementation. Do you have a reproducible, minimal test case for me?

**Comment by arthurschreiber** [comment]
I just checked this again, and the `done` event is fired in the same cases in `1.11` and `1.12`.

**Comment by neverfox** [comment]
I'm having the same issue on 1.13.2. I'm having to rely on the Request callback at the moment.

**Comment by arthurschreiber** [comment]
@neverfox Can you provide a reproducible test case? It's really hard for me to understand how people encounter this issue, as tedious comes with a bunch of unit and integration tests which specifically check that the `done` token is fired correctly.

**Comment by neverfox** [comment]
Let me give it a shot.
