### ISSUE TITLE
requestTimeout not honored

### ISSUE THREAD

**Issue by NamTThai** [pekim/tedious#305]
I have this config file:

```
{
  "userName": "user",
  "password": "pass",
  "server": "shrd-cw",

  "options": {
    "requestTimeout": 0
  }
}

```

However, I still received requestTimeout error:

```
{ [RequestError: Timeout: Request failed to complete in 15000ms]
  name: 'RequestError',
  message: 'Timeout: Request failed to complete in 15000ms',
  code: 'ETIMEOUT' }
```

**Comment by NamTThai** [comment]
When I set `"requestTimeout": 30000` or `400000`, the error will read `Timeout: Request failed to complete in 30000ms`, so I assume the `requestTimeout` parameter works as expected. However, not when I set the value to 0

**Comment by sliontc** [comment]
I got the same issue. Have you solved it?
