### ISSUE TITLE
How to configure a Failover Partner?

### ISSUE THREAD

**Issue by cmeans** [pekim/tedious#315]
In .NET, I'd add something like this to the connection string to set the main server and failover server:

````Data Source=2342878-db1; Failover Partner=61989-db2;````

What are the tedious config properties to use (if it supports this feature)?  (I'm using the node-mssql module and opened the same issue days ago in it's repository with no response as yet.)

**Comment by arthurschreiber** [comment]
There's no way to configure a failover partner at the moment.

You could definately build something around existing tedious functionality, where if the initial connection to your primary data source fails, you reconnect to the failover partner instead.

This would mirror the "Failover Partner" connection string functionality, but it would not mirror all the functionality the .Net driver has for high availability / database mirroring. I checked the documentation for the .Net driver, and apparently SQL Server additionally sends the failover partner information after a successful connection was established, and the "Failover Partner" setting in the connection string is only used on the initial connection attempt, but not when a failover happens after the initial connection attempt.

Making this work correctly would require some changes in the innards of `tedious`.

**Comment by cmeans** [comment]
OK.  We'll looking into developing support for this ourselves.  Thanks.

**Comment by bretcope** [comment]
Just to be clear, Database Mirroring is a deprecated feature of SQL Server.

> This feature will be removed in a future version of Microsoft SQL Server. Avoid using this feature in new development work, and plan to modify applications that currently use this feature. We recommend that you use AlwaysOn Availability Groups instead.

([Source](https://msdn.microsoft.com/en-us/library/ms190202.aspx))

Tedious _does_ support AlwaysOn Availability Groups. If possible, I would suggest looking into migrating to that solution.

**Comment by cmeans** [comment]
Thanks.  We are currently on SQL Server 2012, we are aware of the loss of
support for Mirroring in later versions of SQL Server...given the cost of
AlwaysOn etc we'll likely investigate other backend solutions.
