### ISSUE TITLE
Querying SQL Azure Data Warehouse returning RequestError

### ISSUE THREAD

**Issue by chriskinsman** [pekim/tedious#320]
I have been able to get CREATE TABLE and INSERT statements working.  

A select statement that runs fine in SSDT is failing with: RequestError: Unsupported parameter type found while parsing RPC request. The request has been terminated.

I am not sending any parameters with this request. 

I suspect it may be related to how you stuff the query into a parameter called statement and then call sp_executesql.  Azure SQL Data Warehouse doesn't support varchar(max) and that looks to be causing an issue as my statement is ~8300 characters.  

I tried lengthening the varchar to 9000 characters but now the error shifts to: 

RequestError: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 1 ("@statement"): Data type 0xE7 has an invalid data length or metadata length.

Any thoughts on how to get past this?

**Comment by khkiley** [comment]
Good morning @chriskinsman , I know this is an ancient thread, but I am bumping into a very similar issue. You mention you had been able to get CREATE TABLE to work, do you remember what needed to be done ? I'm creating a table with a lot of columns and the text of the statement is over 17K characters.

Thanks.
