### ISSUE TITLE
nvarchar(max) columns cause tedious to never complete on mssql 2005

### ISSUE THREAD

**Issue by cloudkite** [pekim/tedious#327]
Having trouble executing query that selects a column that is of type `nvarchar(max)` On version 1.12.0+ and mssql 2005. Same query runs fine on mssql 2014.

Query seems to execute without error, I can see that it is completed in SQL profiler. However the request call back or done events are never called.

Reverted tedious back to 1.11.5 and query runs fine. Seems to be a bug introduced in 1.12.0.

Note retrieving columns that are nvarchar with specific length ie `nvarchar(254)` runs fine on either tedious version

**Comment by arthurschreiber** [comment]
Ugh, that's unfortunate. AppVeyor CI only supports SQL Server 2008+, so that's most likely the reason why it works on 2008+, and no one noticed it failing on 2005.

**Comment by arthurschreiber** [comment]
This must be caused by the following code lines: https://github.com/pekim/tedious/blob/v1.12.3/src/value-parser.coffee#L251-L289

Can you take a stab at debugging this, as I don't have sql server 2005 available on my machine right now?

**Comment by cloudkite** [comment]
Hopefully will get a chance to have a look next week, thanks
