### ISSUE TITLE
Data type 0x2A has an invalid data length or metadata length

### ISSUE THREAD

**Issue by pawelrychlik** [pekim/tedious#335]
I have bad luck bumping tedious version from 1.12.7 to 1.13.0. I keep getting the following error:
```
Error: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Parameter 4 ("@createdAt"): Data type 0x2A has an invalid data length or metadata length.
```

Query with params:
```
insert into app.Certificates (clockSkew, createdAt) values (@clockSkew, @createdAt)
[{"name":"clockSkew","value":331155,"type":"int"},{"name":"createdAt","value":"2015-10-27T18:30:26.260Z","type":"datetime2"}]
```

My database is hosted on Azure.

**Comment by pawelrychlik** [comment]
It looks somewhat related to https://github.com/pekim/tedious/issues/320

**Comment by sentient** [comment]
Also running into this isseu on 1.13.0
Trying to look at the changelog http://pekim.github.io/tedious/changelog.html 
but that stops at 1.11

Is it best to rollback to 1.12.?

**Comment by arthurschreiber** [comment]
I'll take a look ASAP.

**Comment by pawelrychlik** [comment]
@sentient changelog seems to have been moved to github/releases at some point https://github.com/pekim/tedious/releases

**Comment by Felix-N** [comment]
@sentient we rolled back to 1.12.7 for now, which works in avoiding the mentioned error.

**Comment by pawelrychlik** [comment]
@Felix-N 1.12.3 to be precise ;)

**Comment by arthurschreiber** [comment]
See #336.

**Comment by pawelrychlik** [comment]
That was quick :)
1.13.1 works just fine. Thanks! :+1:

**Comment by sentient** [comment]
1.13.1 is working for me! 

Thank you for this very fast fix @arthurschreiber

**Comment by harshyadav9** [comment]
Hi i m using tedious version ^5.0.3 to connect and fetch procedure from azure table. but i am getting "Data type 0xAF has an invalid data length or metadata length. " error when calling a stored procedure. kindly healp
