### ISSUE TITLE
Can't connect to any SQL 2012 instance

### ISSUE THREAD

**Issue by leemm** [pekim/tedious#341]
Hi all,
I'm convinced this something relevant to my set up but I'm at a loss as to how to debug it.  Any help would be grateful.

Using 1.13.1 I get this strange error when making a request.

> <path>/node_modules/tedious/node_modules/babel-runtime/helpers/class-call-check.js:5
> throw new TypeError("Cannot call a class as a function");

The connection debug event states the connection open and was successful (as far as I can tell)

> connected to <ip>:undefined
> State change: Connecting -> SentPrelogin
> State change: SentPrelogin -> SentLogin7WithStandardLogin
> Packet size changed from 4096 to 4096
> State change: SentLogin7WithStandardLogin -> LoggedInSendingInitialSql
> State change: LoggedInSendingInitialSql -> LoggedIn

This is code I'm using.  Although password isn't supplied I can assure that it is correct.

```javascript
var tediousConnection = require('tedious').Connection,
	Request = require('tedious').Request;

var sqlConnection = new tediousConnection({
    "server": "<ip>",
	"userName": "sa",
    "password": "<password>",
    "options": {
    	"instanceName": "INST1",
    	"database": "<database>",
    	//"requestTimeout": 0
    }
});

sqlConnection.on('connect', function(err) {
	if (err){ console.log(err); return; }

	var request = Request('SELECT Name FROM sys.tables WHERE is_ms_shipped = 0', function(err, rowCount){
		console.log(err, rowCount);
	});

	console.log(request);

	sqlConnection.execSql(request);

});

sqlConnection.on('debug', function(message) {
	console.log(message);
});
```

**Comment by Mike-Dunton** [comment]
Missing the new keyword before your Request Constructor. 
```javascript
 var request = new Request('SELECT Name FROM sys.tables WHERE is_ms_shipped = 0', function(err, rowCount){
        console.log(err, rowCount);
    });

    console.log(request);

    sqlConnection.execSql(request);

});

```

**Comment by leemm** [comment]
*Sigh*

I knew there was *something* but it was one of those situations where I simply couldn't pin it down.  To be honest the thrown Error now makes sense.

Thanks Mike!

**Comment by Mike-Dunton** [comment]
No problem. Have a good day!

**Comment by arthurschreiber** [comment]
Closing this as the issue was resolved. Happy Holidays!
