### ISSUE TITLE
Understanding request events

### ISSUE THREAD

**Issue by jeremyalan** [pekim/tedious#342]
This might just be a training issue on my part, I'm just trying to figure out how to properly interpret the events being raised when I call the stored procedure...

I have a decently complex stored procedure, it creates and populates a TABLE variable, via a few CTEs and a final select, then returns 2 result sets, and an output parameter.  Pretty much the full spectrum, right? :)

So, here's my dilemma... when I log the events being raised on the call, here's what I see:

::tedious:: [doneInProc]
::tedious:: [doneInProc]
::tedious:: [doneInProc]
::tedious:: [doneInProc]
::tedious:: [doneInProc]
::tedious:: [doneInProc]
::tedious:: [returnValue]
::tedious:: [doneProc]

It appears that I'm receiving 'doneInProc' for each SELECT that gets executed, including the statements that I'm using to populate CTEs and table variables.  My intention was to use the 'doneInProc' events to keep track of which result set I'm iterating on, so how do I determine which statements represent my result sets, so I can ignore the others?

Thanks!

**Comment by lee-houghton** [comment]
You can add "set nocount on" before calling the procedure, or inside the
procedure.

I meant to add a method of overriding  Connection::getInitialSql() for one
of my earlier issues, which would let you set this for all connections, but
I don't think I got round to it. You could always duck punch it as I did in
#230, although that's a little nasty ☺

**Comment by jeremyalan** [comment]
@lee-houghton Awesome!  I was hoping it was just a simple change, and not something that would cause me to re-think my whole approach. (I hate when that happens...) :)

I won't be able to try it out tonight, but I'll try to report back shortly so we can close this issue.

Thanks!

**Comment by jeremyalan** [comment]
It works great, thanks!
