### ISSUE TITLE
Request error: { message: 'Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state',   code: 'EINVALIDSTATE' }

### ISSUE THREAD

**Issue by georgepaoli** [pekim/tedious#344]
Hello,

I get fallowing error on my test of request:

> 'Requests can only be made in the LoggedIn state, not the SentLogin7WithStandardLogin state', code: 'EINVALIDSTATE'

My code (from example of http://pekim.github.io/tedious/getting-started.html):
```javascript
var Connection = require('tedious').Connection;

//var config = {...};

var connection = new Connection(config);

connection.on('connect', function (err) {
    var Request = require('tedious').Request;
    request = new Request("select 42, 'hello world'", function (err, rowCount) {
        if (err) {
            console.log('ERROR');
            console.log(err);
        } else {
            console.log(rowCount + ' rows');
        }
    });

    request.on('row', function (columns) {
        columns.forEach(function (column) {
            console.log(column.value);
        });
    });

    connection.execSql(request);
});
```
Thanks in advance.

**Comment by arthurschreiber** [comment]
It looks like you are not handling the pottential `err` parameter on the `connect` event. If the connection failed and `err` is not undefined, trying to execute a request will raise the same error as you are describing.

**Comment by georgepaoli** [comment]
Thanks arthurschreiber!

`err` parameter on the `connect` event return following message:
> { message: 'Failed to connect to `<my ip sql server>`:1433 in 15000ms', code: 'ETIMEOUT' }

**Comment by 1311543** [comment]
Running Promises in SequenceSection
/**
 * Runs promises from array of functions that can return promises
 * in chained manner
 *
 * @param {array} arr - promise arr
 * @return {Object} promise object
 */
function runPromiseInSequence(arr, input) {
  return arr.reduce(
    (promiseChain, currentFunction) => promiseChain.then(currentFunction),
    Promise.resolve(input)
  );
}

**Comment by 1311543** [comment]
sorry if i dont explain so clear but i resolve the problem chainning the request with reduces
cqlStatements.map( stmt =>
                (result) => {
                    return connection.openConnection()
                    .then( cn => cn.executeStatement(stmt))})
                    .reduce((p, fn) => p.then(fn), Promise.resolve())
