### ISSUE TITLE
How do I pass Additional Connection Parameters

### ISSUE THREAD

**Issue by mithun-daa** [pekim/tedious#345]
I need to set the following setting on the connection:
````
multisubnetfailover=true
````

Is this supported? I enter it while connecting to our databases on the Connect to Server modal.
Connect to Server -> Options -> Additional Connection Parameters

![image](https://cloud.githubusercontent.com/assets/852171/11533643/68a7a248-98d0-11e5-9063-8d546ca98047.png)

**Comment by arthurschreiber** [comment]
`multisubnetfailover` is not supported yet, but work on making this functionality available is underway. :smile:

**Comment by mithun-daa** [comment]
Ok thanks! Do you know any other module that supports `multisubnetfailover` ?

**Comment by arthurschreiber** [comment]
No, I don't think there's any other viable TDS driver for node.js except for `tedious`.

**Comment by mithun-daa** [comment]
Thank you!

**Comment by arthurschreiber** [comment]
Once #362 gets merged and released, `tedious` will support multi subnet failover.

**Comment by mithun-daa** [comment]
:+1:
