### ISSUE TITLE
Saving result of multiple select-statements in one array?

### ISSUE THREAD

**Issue by boredSinan** [pekim/tedious#349]
Hi everybody,
##### When I run the following code, the output looks like:
![image](https://cloud.githubusercontent.com/assets/7433300/11813765/59e473d0-a343-11e5-87f8-02f69b78ea89.png)

##### So here is my problem:
I want to write the result of the first select-statement in the array "select_result ", display its content
and delete/overwrite its content for the next select-statement. But as you can see in the screenshot, the results of all 3 select-statements are stored in the array. The event "request.on()" is somehow executing all 3 select-statements simultaneously?

##### Here is the code:

```javascript

var ConnectionPool = require('tedious-connection-pool');
var Request = require('tedious').Request;

var connectionConfig = {
    server: 'MSserver',
    userName: 'user',
    password: 'password',
    options: {
        database: 'databaseName',
        port: 55555
    }
};

var poolConfig = {
    min: 1,
    max: 10,
    log: true
};

//Define a pool:
var pool = new ConnectionPool(poolConfig, connectionConfig);

var select_result = [];
var loop_count = 0;

//Execute SQL SELECT commands
execute_SELECT_Statement('SELECT ID FROM table');
//select_result = [];
//display_Select_Result(select_result);

execute_SELECT_Statement('SELECT Room FROM table');
//select_result = [];
//display_Select_Result(select_result);

execute_SELECT_Statement('SELECT Floor FROM table');
//select_result = [];

display_Select_Result(select_result);

/*
 * Function which selects from database-tables
 */
function execute_SELECT_Statement(sql_statement) {

    pool.acquire(function(err, connection) {
        if (err)
            console.error(err);

        //use the connection as normal
        var request = new Request(sql_statement, function(err, rowCount) {
            if (err)
                console.error(err);

            //release the connection back to the pool when finished
            connection.release();
        });

        connection.execSql(request);

        request.on('row', function(columns) {
            console.log('loop_count: ' + loop_count);
            select_result[loop_count] = columns[0].value;
            loop_count++;
        });
        //pool.drain();
    });
   loop_count = 0;
}

/*
 * Function which displays content of any array
 */
function display_Select_Result(select_result) {
    for (var l = 0; l < select_result.length; l++) {
        console.log('[' + l + ': ' + select_result[l] + '\n');
    }
}

```

**Comment by ben-page** [comment]
https://github.com/pekim/tedious-connection-pool/issues/26

You posted essentially the same question on my project, Tedious Connection Pool. What you are reporting is not a bug in either library. Your questions are really about basic programming technique. 

That said, I did post several pointers that I hope are helpful to you. But, the github Issue Tracker is for reporting bugs in the library not general help. For more help, I suggest you use stackoverflow.com. That community is very capable of helping you learn and solve these issues.

**Comment by boredSinan** [comment]
Hi ben-page,
thank you for your tips. 
I am new to Github and Javascript. Therefore I wanted to post my questions on Github, because I wanted to ask you (because its your project) directly.
