### ISSUE TITLE
RequestError on multiple parallel queries using one connection

### ISSUE THREAD

**Issue by drywolf** [pekim/tedious#355]
Hi,

I'm using tedious to execute simple SQL queries by using one shared connection.
The TDS queries/requests are triggered from an Express.js route, therefore many simultaneous requests could be executing at the same time, if the frequency of the incoming HTTP requests from the client is high enough.

When a HTTP request comes in, while another TDS request is still being handled by tedious, I get this error:
    Requests can only be made in the LoggedIn state, not the SentClientRequest state
    at RequestError (...\\node_modules\\tedious\\lib\\errors.js:42:12)

As long as the TDS requests can complete one after the other before the next HTTP request comes in, this error does not happen (at least that's what I get from the basic trials that I did).

Also, it looks like the people over at sequelize are also experiencing this problem in some way sequelize/sequelize#4105.

Does tedious support queuing multiple requests out of the box, or does this need to be handled by user-code ?
Meaning that if a TDS-request is currently active, is it forbidden to create another `Request(sql, (err, count) { ... })` and execute it on the same connection ?

Thanks,
Regards Wolfgang

**Comment by drywolf** [comment]
Sorry, I just realized that this is not supported by design, after I found [this issue](https://github.com/pekim/tedious/issues/19#issuecomment-5137666) discussing the same usecase.

... and read the documentation on [new Request](http://pekim.github.io/tedious/api-request.html#function_newRequest) more carefully ;)

Can someone give some hints though how to properly manage this situation though ?
Should I look at using pekim/tedious-connection-pool or coopernurse/node-pool to get support for multiple concurrent requests.

Thanks

**Comment by arthurschreiber** [comment]
Hey @drywolf,

as you seem to have already found out, tedious does not support request queueing out of the box, and the preferred solution is to use a connection pool. You're free to use on of the existing modules or roll your own. :smile:

**Comment by drywolf** [comment]
Thanks for the reply.
I'm already using tedious-connection-pool and the first tests worked flawlessly.
I hope these comments will help people in the future if they bump into the same question :smile: :wink:
