### ISSUE TITLE
Reconnection on connection timeout

### ISSUE THREAD

**Issue by exinferis** [pekim/tedious#359]
When the db server is not reachable, tedious correctly runs into a timeout and will correctly report this to the connect event.

Is there a way that tedious enters a reconnection state afterwards, thus trying to reconnect to the sql server automatically? The node redis client does this for example - with increasing intervals.

**Comment by arthurschreiber** [comment]
I don't think `tedious` supports this out-of-the box. I'm also not sure if that's a good idea. Connections to SQLServer carry state, like connection level settings or transactions. Automatically reconnecting will lose this state, which might be **extremely** bad if you have subsequent queries which assume they're being executed in a transaction.

In redis, there is no such thing, so reconnecting automatically is not an issue.

Usually, we recommend people use a connection pool, and reconnecting should be one of the features your connection pool should offer you.
