### ISSUE TITLE
SQL AlwaysOn Availability Groups - MultiSubnetFailover

### ISSUE THREAD

**Issue by closedstack** [pekim/tedious#360]
SQL Server 2012 onwards has the concept of Availability groups and  to provide high availability locally as well as at remote sites. It also allows you to load balance connections that are only running readonly workloads to secondary replicas. 

If a site becomes unavailable - you can have the instance at a remote site take over the workload - but to make this possible, you have to put 2 (or more) IPs in the DNS for the listener, since the IP from Subnet in SiteA will not fail over to subnet in SiteB..

How can we get Tedious to support the newer SQL Server features including Application Intent and MultiSubnetFailover?

https://msdn.microsoft.com/en-us/library/gg471494(v=sql.120).aspx

**Comment by arthurschreiber** [comment]
Please see #362 for a correct implementation of availability groups via DNS.
