### ISSUE TITLE
Does the addParameter method for request have SQL Injection protection

### ISSUE THREAD

**Issue by himion0** [pekim/tedious#369]
Hi I just wanted to know if this is the case. I.e. does the method remove/escape the '/" characters for example?

**Comment by bretcope** [comment]
Simply answer: yes.

More correct answer: Parameters are part of the TDS protocol. They're not inlined into the SQL itself, and therefore don't need to be escaped. Parameters are not only safer than inlining, they also allow SQL Server to cache query plans, which makes your queries run more efficiently.
