### ISSUE TITLE
Performance issue?

### ISSUE THREAD

**Issue by mhingston** [pekim/tedious#370]
SQL Server 2008 R2, Node 5.7.0, TDS 7.4 (default configuration, only custom config is for increased requestTimeout).

I've noticed when calling a particular parameterized stored procedure within a database that tedious is taking an exceptionally long time for the request to complete. I've setup a test case on the database server itself to rule out any network latency and it still takes the same amount of time as running the query from a different server in the same data centre. In SSMS calling the SP takes ~22ms to complete, when calling the same SP with the same parameters via tedious (using execSQL or callProcedure) it takes around 55 seconds for the request to complete. I've turned on all debugging options and as far as I can tell there is nothing being emitted that explains why this is happening... [debug snippet below]

      RPC Request - sp_executesql
    State change: LoggedIn -> SentClientRequest

Then ~55 seconds later the next thing printed is the response...

    Received
      type:0x04(TABULAR_RESULT), status:0x01(EOM), length:0x0FF5, spid:0x0037, packetId:0x01, window:0x00

**Comment by arthurschreiber** [comment]
Hey @mhingston.

Is this just happening with one specific stored procedure? How much data is returned by it? Can you share the code of the stored procedure and the data?

**Comment by mhingston** [comment]
I've only noticed it on [this particular stored procedure](https://github.com/pekim/tedious/files/151362/email_clicks.sql.txt), it's bringing back 17 rows with 13 columns, the data types are just Int, DateTime and NVarChar.

I've copied the database tables used by the stored procedure to a new database, have re-indexed them and truncated the database to less than 200MB as well as taking out the sensitive data but when I repeat the test in this new database the request completes in ~259 ms from tedious. In the production db the largest table being queried has about 20 millions rows and there are others being used by the stored procedure that have several million. I don't realistically have a way to get the data to you, like-for-like, the dataset is too large.

I've just tried recreating the same stored procedure with a different name with the intent to try and and take it apart and find what causes the bottleneck. Anyway, out of curiosity I called this new stored procedure and the request from tedious completes in ~96 ms. Amazed, I diffed the two stored procedures and they are exactly the same apart from the name yet the original takes ~55 seconds. I'm confused? Either way I appear to have resolved the issue so I will close this.

**Comment by bretcope** [comment]
@mhingston it could have been a very bad query plan cached for calling the SP. When you called an identical SP except for name, it would also create a new plan, which was perhaps much better. Did you try using [DBCC FREEPROCCACHE](https://msdn.microsoft.com/en-us/library/ms174283.aspx) to clear the plan cache and see if the original SP performance improved? Perhaps irrelevant now, but something to consider if you run into it again.

**Comment by yosiasz** [comment]
that is a scary sproc. you got a lot going on in that sproc. the issue is more with the sproc and tedious is exposing it
for example #EmailClick. no index.
create table #EmailClick
insert into #EmailClick
create index you will be joining to it with
way outside of tedious' scope..sorry
