### ISSUE TITLE
[ECONNREFUSED] running on node-red chrome

### ISSUE THREAD

**Issue by luiey** [pekim/tedious#371]
Hi,

I was just playing with node-red. Very new to write java. How to connect to mssql database?
Database installed: MSSQL 2008 Express.
Browser:Google Chrome

I already trying connect using Function and MSSQL nodes separately but both failed.
Function code:-
```
// Query with explicit connection
var sql = require('node-sqlserver');
var conn_str = "Driver={SQL Server Native Client 11.0};Server=(localhost);Database=smart_iot;Trusted_Connection={Yes}";

sql.open(conn_str, function (err, conn) {
    if (err) {
        msg.payload="Error opening the connection!";
        return;
    }
    conn.queryRaw("SELECT TOP 10 ID, str_name, dtm_date FROM dbo.tbl_supplier", function (err, results) {
        if (err) {
            msg.payload="Error running query!";
            return;
        }
        for (var i = 0; i < results.rows.length; i++) {
            msg.payload="FirstName: " + results.rows[i][0] + " LastName: " + results.rows[i][1];
        }
    });
});
return msg;
```

Nodes:-
![mssqlcn](https://cloud.githubusercontent.com/assets/17740673/13732717/f57892ce-e9c3-11e5-9b9b-2a83bdbedace.png)

Nodejs:-
![nodejs](https://cloud.githubusercontent.com/assets/17740673/13732748/4d9dc410-e9c4-11e5-82ec-43b8b52bcf07.png)

Node Modules:-
![nodes](https://cloud.githubusercontent.com/assets/17740673/13732768/7326cee8-e9c4-11e5-8937-162565204fce.png)

Services:-
![services](https://cloud.githubusercontent.com/assets/17740673/13732799/c2e3c8fa-e9c4-11e5-88c5-a2a357e9052e.png)

Note:- Already enable TCP/IP under SQL Server Configuration Manager

**Comment by bretcope** [comment]
It looks like you're using [node-sqlserver](https://github.com/Azure/node-sqlserver). Tedious has nothing to do with that project.

**Comment by luiey** [comment]
Hi @bretcope 

I was new in Github and node and java. Thought I might sending wrong issue to your site. My apologies for that. I will pass the question to the link. Thanks
