### ISSUE TITLE
Performance issue with too many columns

### ISSUE THREAD

**Issue by bergi9** [pekim/tedious#372]
SQLServer 2012, Node 5.7, Default Configuration
I have a table with 79 columns.
If i query with `SELECT * FROM table WHERE Num = @Num`, which returns only single row, it takes ~420ms.
If i query with `SELECT Num FROM table WHERE Num = @Num`, which returns one column and one row, it takes ~2ms.
I have test it with concurrent connections (tedious-connection-pool), which returns the same times on same queries.
The highest CPU utilization was 1% by benchmarking with concurrent connections.

**Comment by lee-houghton** [comment]
Are there any large text/binary columns in this table?

How long does it take using another library such as ADO.NET or ODBC, or tool such as sqlcmd or SQL Server Management Studio?

**Comment by bergi9** [comment]
It turns out the delay was from the VPN connection. I'm sorry to created the issue.
After testing via ADO.NET it has the same issue too until i moved to localhost.
