### ISSUE TITLE
Question : bigint as number support might be extended

### ISSUE THREAD

**Issue by sandorfr** [pekim/tedious#389]
Currently bigint must be passed as string if they are outside of this range [[-214748.3648, 214748.3647]](https://github.com/pekim/tedious/blob/50e76efdcd87f687106c722d54c6ea4096f0a127/src/data-type.js#L573).

According to [MDN documentation](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/MIN_SAFE_INTEGER) this could be extended to [-9007199254740991, 9007199254740991].

Is there a particular reason not to do so?

**Comment by lee-houghton** [comment]
You're looking at the validation code for SmallMoney there - those limits
for SmallMoney look correct to me. BigInt seems to do very little in its
validation function.

**Comment by sandorfr** [comment]
yes my bad :). 

The error I get is actually `Unhandled rejection RequestError: Validation failed for parameter 'p0'. Value must be between -2147483648 and 2147483647.`.

It seems to come from [int4](https://github.com/pekim/tedious/blob/50e76efdcd87f687106c722d54c6ea4096f0a127/src/data-type.js#L158). 

So, I think number as js type defaults to int4 which is indeed limited to that range.

**Comment by sandorfr** [comment]
Thanks @lee-houghton  pointed me in the right direction.
