### ISSUE TITLE
Can't connect to DB that has Cluster setup; Need workaround for MultiSubnetFailover non-support. 

### ISSUE THREAD

**Issue by jblaketc** [pekim/tedious#396]
Apparently the only way to connect to this database we have no control over is by supplying the MultiSubnetFailover flag, otherwise the connection times out. I increased the connectTimeout and requestTimeout, but I get an ESOCKET code with a ultimate timeout. 

How do I go about connecting with tedious in this situation if the MultiSubnetFailover flag isn't supported. Anyone know a workaround?

Thanks!

**Comment by mitant** [comment]
see #362 for a contributor's attempt to get it to work.  Let's try and help Arthur test his change and get it working and merged!

**Comment by jblaketc** [comment]
@mitant Actually ya I ended up switching to that branch and putting that code in the server modules. It connects fine with cluster and localhost dbs. I haven't run into any issues with it so far. Anything else I need to test to make it ready for merging?

**Comment by mitant** [comment]
I recommend supplying the same positive feedback in #362 .  I'm not sure why it didn't work for me.  Not sure if my DB setup is different or maybe I didn't load the pull request correctly.  For me constant activity would lead to occasional timeouts for some calls.  Maybe some sort of prolonged stress test would be good to try
